### ISSUE TITLE
Missing dependences.

### ISSUE THREAD

**Issue by lessu** [franckLdx/gulp-useTsConfig#1]
It shows error while running example in OSX.

`$ gulp build`

> 
> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'tslint'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (****(hide)/node_modules/gulp-tslint/index.js:6:14)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
> 

I think you've forgot to add dependences.
fixed after running 

`$ npm install --savedev tslint`

**Comment by franckLdx** [comment]
You're right. tslint is in devDependencies, so that is not installed when this project is in your deps. The new release 1.1.5 fix this.
Thanks
